spring.application.name=LoyalBridge
spring.datasource.url=jdbc:postgresql://localhost:5432/LoyalBridge
spring.datasource.username=postgres
spring.datasource.password=rusira

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger
springdoc.api-docs.path=/api-docs
